# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'harmay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for harmay

  pod 'SDAutoLayout'
  pod 'MMDrawerController'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'AFNetworking'

end
