platform:ios, '8.0'
target 'HARMAY_PI_BRAND’ do
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry'
    pod 'IQKeyboardManager', '~> 3.3.4'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'RESideMenu', '~> 4.0.7'
end
